import Navigation from './components/Navigation'
import { Space_Grotesk } from '@next/font/google'
import '../../styles/globals.css'

export const metadata = {
  title: 'My first app with next js',
  description: 'Generated by Cristian Valles',
}

const font = Space_Grotesk({
  weight: ["400", "700"],
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
